---
- name: Deploy NGINX Web Server using Docker
  hosts: localhost
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: true

    - name: Run NGINX Container
      docker_container:
        name: ca1-nginx
        image: nginx
        ports:
          - "80:80"
